defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Edgar Luiz de Lima
subtitle: Ecologist and Data Analyst. Theoretical Ecology researcher, PhD student in Ecology. 

left_side:
  background_image: "./assets/images/image2.jpg"
  background_color: "#0000FF"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Bio
    link: /
    icon: ""
    
  - text: Portfolio
    link: /portifolio
    icon: ""
    layout: default
     
  - text: Academic projects
    link: /project
    icon: ""
    layout: default 
 
# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/edgar-luiz-de-lima-35646851/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/edgar-lima
    icon: fab fa-github-square

  - name: twitter
    link: https://twitter.com/EdgarLuizdelim1
    icon: fab fa-twitter
    
  - name: medium
    link: https://medium.com/@edgarluizdelima
    icon: fab fa-medium
    
 - name: researchgate
    link: https://www.researchgate.net/profile/Edgar_Luiz_De_Lima
    icon: fab fa-researchgate  
