defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Edgar Luiz de Lima
subtitle: Ecologist and Data Analyst. Theoretical Ecology researcher, PhD student in Ecology. 

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Resume
    link: /
    icon: ""
    
  - text: Portifolio
    link: /_Portfolio
    icon: ""
           
  - text: Academic projects
    link: /project
    icon: ""

  - text: Curriculum vitae
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/edgar-luiz-de-lima-35646851/
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/edgar-lima
    icon: fab fa-github-square

  - name: twitter
    link: https://twitter.com/EdgarLuizdelim1
    icon: fab fa-twitter
    
  - name: orcid
    link: https://orcid.org/0000-0002-3459-9248
    icon: fab fa-orcid


    
